#!/bin/bash

# Обновляем пакеты
apt update

# Устанавливаем необходимые инструменты для сборки
apt-get install build-essential -y

# Скачиваем и распаковываем исходники 3proxy
wget https://github.com/z3APA3A/3proxy/archive/0.9.3.tar.gz
tar xzf 0.9.3.tar.gz
cd 3proxy-*

# Добавляем опцию ANONYMOUS в исходники
sed -i '1s/^/#define ANONYMOUS 1\n/' ./src/proxy.h

# Собираем 3proxy
make -f Makefile.Linux

# Создаем каталоги для логов и конфигурации
mkdir -p /var/log/3proxy
mkdir /etc/3proxy

# Копируем бинарный файл 3proxy в /usr/bin/
cp bin/3proxy /usr/bin/

# Вводим пароль с клавиатуры
read -p "Введите пароль для пользователя: " password

# Создаем файл конфигурации 3proxy
cat <<EOF | sudo tee /etc/3proxy/3proxy.cfg >/dev/null
nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1

nscache 65536
timeouts 1 5 30 60 180 1800 15 60

daemon

log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

auth strong

allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS

proxy -p53129 -n -a
users user:CL:$password

EOF

# Создаем файл systemd для 3proxy
cat <<EOF | sudo tee /etc/systemd/system/3proxy.service >/dev/null
[Unit]
Description=3proxy Proxy Server

[Service]
Type=simple
ExecStart=/usr/bin/3proxy /etc/3proxy/3proxy.cfg
ExecStop=/bin/kill \$(/usr/bin/pgrep -u proxy3)
RemainAfterExit=yes
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# Перезапускаем 3proxy и включаем его автозапуск
systemctl daemon-reload
systemctl restart 3proxy
systemctl enable 3proxy
